=== raml-apis/AzureTableStorage/schemas/entityInsertResponseNoMeta-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "PartitionKey" : {
      "type" : "string" ,
      "required" : false
    } ,
    "RowKey" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Timestamp" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Address" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Age" : {
      "type" : "number" ,
      "required" : false
    } ,
    "AmountDue" : {
      "type" : "number" ,
      "required" : false
    } ,
    "CustomerCode" : {
      "type" : "string" ,
      "required" : false
    } ,
    "CustomerSince" : {
      "type" : "string" ,
      "required" : false
    } ,
    "IsActive" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "NumberOfOrders" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/AzureTableStorage/examples/entityInsertResponseNoMeta-example.json
{
  "PartitionKey" : "mypartitionkey" ,
  "RowKey" : "myrowkey" ,
  "Timestamp" : "2013-08-22T01:12:06.2608595Z" ,
  "Address" : "Mountain View" ,
  "Age" : 23 ,
  "AmountDue" : 200.23 ,
  "CustomerCode" : "c9da6455-213d-42c9-9a79-3e9149a57833" ,
  "CustomerSince" : "2008-07-10T00:00:00" ,
  "IsActive" : true ,
  "NumberOfOrders" : "255"
}
