=== raml-apis/AzureTableStorage/schemas/entityInsert-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "Address" : {
      "type" : "string" ,
      "required" : false
    } ,
    "Age" : {
      "type" : "number" ,
      "required" : false
    } ,
    "AmountDue" : {
      "type" : "number" ,
      "required" : false
    } ,
    "CustomerCode@odata.type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "CustomerCode" : {
      "type" : "string" ,
      "required" : false
    } ,
    "CustomerSince@odata.type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "CustomerSince" : {
      "type" : "string" ,
      "required" : false
    } ,
    "IsActive" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "NumberOfOrders@odata.type" : {
      "type" : "string" ,
      "required" : false
    } ,
    "NumberOfOrders" : {
      "type" : "string" ,
      "required" : false
    } ,
    "PartitionKey" : {
      "type" : "string" ,
      "required" : false
    } ,
    "RowKey" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/AzureTableStorage/examples/entityInsert-example.json
{
  "Address" : "Mountain View" ,
  "Age" : 23 ,
  "AmountDue" : 200.23 ,
  "CustomerCode@odata.type" : "Edm.Guid" ,
  "CustomerCode" : "c9da6455-213d-42c9-9a79-3e9149a57833" ,
  "CustomerSince@odata.type" : "Edm.DateTime" ,
  "CustomerSince" : "2008-07-10T00:00:00" ,
  "IsActive" : true ,
  "NumberOfOrders@odata.type" : "Edm.Int64" ,
  "NumberOfOrders" : "255" ,
  "PartitionKey" : "mypartitionkey" ,
  "RowKey" : "myrowkey"
}
